const router = require('express').Router()
const noticias = require('../controllers/noticias.controller')
const users = require('../controllers/users.controller')
const racio = require('../controllers/racio.controller')

router.post('/racio/post', racio.racioController.novoRacio)
router.get('/racio/find', racio.racioController.apresentarRacio)
router.put('/racio/post/', racio.racioController.editarRacio)
router.get('/findG', noticias.noticiasController.noticiasDaSemana)
router.get('/posts', noticias.noticiasController.noticiasDaSemana)
router.get('/find/:id', noticias.noticiasController.encontrarUmaNoticia)
router.get('/finds/:categoria', noticias.noticiasController.encontrarNoticiaPorCategoria)
router.get('/findN', noticias.noticiasController.encontrarNoticiaPorTitulo)
router.get('/noticia/numSemanas/:data0/:data1', noticias.noticiasController.noticiasNumeroSemanas)
router.get('/noticia/numSemanasCateg/:data0/:data1/:categoria', noticias.noticiasController.noticiasNumeroSemanasCateg)
router.get('/findIdCate/:id/:categoria', noticias.noticiasController.encontrarUmaNoticiaPorCategoriaEIdUtilizador)
router.post('/users/post', users.usersController.novoUser)
router.put('/post/:id', noticias.noticiasController.editarNoticia)
router.get('/users/findE/:email', users.usersController.encontrarUsersEmail)
router.post('/Authenticate', users.usersController.authenticateUser)
router.get('/check',  users.usersController.checkToken)
router.use( users.usersController.protectRoutes)
router.get('/noticia/find/:id', noticias.noticiasController.encontrarNoticiaPorIdUtilizador)
router.delete('/delete/:id', noticias.noticiasController.apagarNoticia)
router.post('/post', noticias.noticiasController.novaNoticia)
router.get('/noticiasNovas/find', noticias.noticiasController.encontrarNovasNoticias)
router.put('/estadoNoticia/post/:id', noticias.noticiasController.atualizarEstado)
router.get('/users/posts', users.usersController.listarTodosUsers)
router.get('/users/find/:id', users.usersController.encontrarUmUser)
router.put('/users/post/:id', users.usersController.atualizarEstado)
router.delete('/users/delete/:id', users.usersController.eliminarUser)
router.get('/usersNovos/find', users.usersController.encontrarUsersNovos)
router.put('/users/posts/:id',users.usersController.atualizarPassword)


module.exports = router


